### PR TITLE
Error handling/reporting improvements, BER MemberType decode performance improvements and support for decoding fields in any order

### PR DESCRIPTION
**Pull request by Finndersen**
**BER MemberType decode performance improvements**
BER types now return a DECODE_ERROR value instead of DecodeTagError when there is a tag mismatch, so MemberType can handle this case faster than catching exception.

Re-worked implementation of MemberType.decode() so that it now supports decoding data with fields encoded in different order than specified in schema. This rework also improves performance by reducing number of function calls.

These two changes together result in improved performance of decoding BER data with many optional SEQUENCE or SET elements by up to 25% (for example for GPRS records with schema: [GPRSRecord](https://cs.fit.edu/code/projects/cse2410spring2014_team4/repository/revisions/master/entry/asn1/gprscdr/GPRSChargingDataTypesV1171.asn))

**Improved Error handling and reporting**
DecodeError, EncodeError and ConstraintsError all inherit from ErrorWithLocation exception class which stores error location details.
Instead of MemberTypes catching errors and adding location information, I have added a new @add_error_location decorator which is used to wrap all encode() and decode() methods, and will catch errors and add appropriate location information.
This means that error location information will always be added, not just for errors from elements within a MemberType.  This also means that the root type name can be added to error location as well.

Changed location element formatting to use '.' separator instead of ': '.

Additionally, DecodeError now has an 'offset' attribute which can be provided upon initialization, instead of just formatted into the error message. This means the offset value can be introspected from the exception object, which can be useful, and means offset details are captured for more error scenarios and added to error message in consistent manner (at end of message).

Here are some before and after examples of error messages:

BEFORE: Expected choice member tag '80', but got '81'.
AFTER:   A: Expected choice member tag '80', but got '81'. (At offset: 0)

BEFORE:  Expected ExplicitTag with tag 'a2' at offset 0, but got 'a3'.
AFTER:    Foo: Expected ExplicitTag with tag 'a2', but got 'a3'. (At offset: 0)

BEFORE: data: set-request: variable-bindings: value: Expected choice 'application-wide' or 'simple', but got ''
AFTER:   Message.data.set-request.variable-bindings.value: Expected choice 'application-wide' or 'simple', but got ''

BEFORE: Expected at least 159 contents byte(s) at offset 3, but got 0.
AFTER:   Certificate: Expected at least 159 contents byte(s), but got 0. (At offset: 3)

BEFORE: fum: Bad AnyDefinedBy choice 1.3.1000.8.
AFTER:   Fie.fum: Bad AnyDefinedBy choice 1.3.1000.8. (At offset: 8)

### CODE REVIEW

**Comment by eerimoq** [comment]
Performance improvements are welcome. Could you create a separate PR with only those to give more more time reviewing the rest?

**Comment by Finndersen** [comment]
hey sorry I haven't gotten around to splitting out the changes!

**Comment by Finndersen** [comment]
@eerimoq I have updated the PR, including new change which adds support for decoding BER SET or SEQUENCE data which has fields encoded in different order than specified in schema (which is something that can occur)
This new implementation of MembersType.decode() also improves performance

**Comment by eerimoq** [comment]
I inveted you to be a collaborator, which allows you to merge and publish releases. Feel free to help out making asn1tools better as my interest in the project has dropped recently.

**Comment by Finndersen** [comment]
Great, thank you!

**Pull request merged**
