### PR TITLE
Long addition length bugfix

### PR DESCRIPTION
**Pull request by Futsch1**
I just found a bug that became obvious in the fuzzer: If the addition length is decoded as very large value, the loop determining the unused bits does not stop when reaching the end of the data.

### CODE REVIEW

**Comment by eerimoq** [comment]
Nice find. Add a test and I'll merge.

**Comment by Futsch1** [comment]
> 
> 
> Nice find. Add a test and I'll merge.

I find it hard to create a test for that: It would not result in a fail, but merely run very long (since eventually, even 0xfffffffff loops will be finished). I found it using the fuzzer (question is why I haven't found it earlier, but I seem to have gotten lucky with the random fuzzer patterns). I have not been diving into the fuzzing mechanism, but it should yield a fail when a test runs too long?!?

So although it is possible to create a test, I think that a running fuzzer should be sufficient. What do you think?

**Comment by eerimoq** [comment]
It should be possible to create a decode-test where the addition length is large. The new logic will make the test fail immediately, right?

There is no reason to make all additions-values part of the message to decode, just just the length field is important.

**Comment by Futsch1** [comment]
In fact, you're right, I'll do so right away.

**Pull request merged**
