### PR TITLE
Up to 64 bit sized bit strings supported in C code generator

### LINKED ISSUE #99: bit strings for C
Hi,
Do you consider to support bit string from 32 to 64 or 128 bits for C code generation.
Use int64_t or __int128_t to replace int32_t and use a for loop encoding to replace switch-case.

Sincerely,
Kang

### PR DESCRIPTION
**Pull request by Futsch1**
Closes #99 
Bit strings have only been supported up to 32 bits before. This change provides support for 64 bits. Bit strings larger than 32 bits are encoded and decoded using a new dedicated function in the OER generator (decoder_read_long_uint, encoder_append_long_uint). 

I chose to not reimplement the existing 32 bit based encoding and decoding functions for ints to avoid the generation of functions with 64 bits in cases where it is not required. Introducing the uint64_t type might be an issue for smaller sized embedded systems, it also comes at a performance cost in these systems. So the existing generated code is unchanged, only bit strings with more than 32 bits in length use these new functions.

In addition, I refactored the generators by moving the strings containing the generated C functions to dedicated modules to make the main generator code more clear.

### CODE REVIEW

**Comment by Futsch1** [comment]
@eerimoq: I will wait with merging the PR until Friday to give you the chance to review/comment/object.

**Comment by eerimoq** [comment]
Thanks for implementing this. Much appreciated.

Unfortunately I'm quite busy with the Mys project at the moment so I put my trust in you and @ttt710516. The changes should be fine as long as they don't break any existing functionality.

**Comment by eerimoq** [comment]
I'm out of credits on Travis CI. We should move all testing to Github Actions instead. I can work on this today.

**Comment by eerimoq** [comment]
Now Github Actions is used to test commits and publish releases. I created a new tag, 0.155.0, on master, which has been published to PyPI.

**Pull request merged**
