### PR TITLE
MISRA compliant C source

### PR DESCRIPTION
**Pull request by Futsch1**
I would like to share another change with you: For use in a regulated environment, the adherence of MISRA rules is important and required. I have changed the code generators to reduce the number of MISRA findings the generated code causes. 

For OER, I managed to reduce the findings (almost) to zero, there is just one issue left that is related to a bug (encoding the addition of a sequence with members with variable sizes) I'm going to fix shortly after.
For UPER, I also reduced the number of findings but due to the nature of the encoding, especially findings related to signed/unsigned data types are hard to fix.

### CODE REVIEW

**Comment by eerimoq** [comment]
We should add a test compilation with flags similar to these: https://github.com/eerimoq/cantools/blob/master/Makefile#L32

It will produce a ton of warnings, some which are MISRA rules.

**Comment by Futsch1** [comment]
I added a test to the Makefile, is that how you imagined it?

I will also look into potential helper functions.

**Comment by Futsch1** [comment]
I did not identify any functions that could be moved into helpers... Do you have a suggestion?

**Comment by eerimoq** [comment]
I haven't looked closely for places where helper functions could be useful, no. I just know that `cantools` has functions with _u8/_u16/... suffixes, and that code is very easy to read.

**Comment by eerimoq** [comment]
Yes, that kind of test with gcc and clang looks just fine, thanks!

I think this is ready to be merged, right?

**Comment by Futsch1** [comment]
Yes, I don't plan to add commits to that PR. Go ahead to merge it.

**Pull request merged**
