### PR TITLE
Reworked encode_signed_integer() and decode_signed_integer() implementations for much better performance

### PR DESCRIPTION
**Pull request by Finndersen**
Up to 80% improved performance of Integer Encode:

%%timeit
encode_signed_integer(-1946141750)
2.44 µs ± 201 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

%%timeit
encode_signed_integer_new(-1946141750)
468 ns ± 138 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

Up to 60% improved performance of Integer Decode:

%%timeit
decode_int_old(b'\x8c\x00\x3b\xca')
644 ns ± 48.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%%timeit
decode_int_new(b'\x8c\x00\x3b\xca')
264 ns ± 57.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

### CODE REVIEW

**Comment by Finndersen** [comment]
I don't see why tests are failing.. they pass locally and I haven't changed anything that should impact those

**Comment by Finndersen** [comment]
@eerimoq any idea whats up? The changes I made should have no effect on the failing test cases for codec parsing etc and they all pass on my system

**Comment by eerimoq** [comment]
The problem is that Github Actions installs pyparsing 3.x.y, which is incompatible with asn1tools. All tests pass with pyparsing 2.m.n. I guess we should update asn1tools to be compatible with the latest version of pyparsing.

**Comment by eerimoq** [comment]
asn1tools should work with both old and new pyparsing now.

**Comment by Finndersen** [comment]
Cool, resolved now

**Pull request merged**
